spring:
  application:
    name: catchroom
  datasource:
    url: jdbc-secretsmanager:mysql://catchroomdb.c1aeg6a0abt3.ap-northeast-2.rds.amazonaws.com:3306/catchroomdb
    username: catchroom-secret-manager
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  log:
    slack:
      enabled: true
      channel: #error
      web-hook-url: https://hooks.slack.com/services/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
    database:
      enabled: true

    level: ERROR
