spring:
  application:
    name: catchroom
  datasource:
    url: jdbc-secretsmanager:mysql://catchroomdb.c1aeg6a0abt3.ap-northeast-2.rds.amazonaws.com:3306/catchroomdb
    username: catchroom-secret-manager
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  database:
    enabled: true
  level: ERROR
  data:
    redis:
      host: ec2-3-39-74-198.ap-northeast-2.compute.amazonaws.com
      port: 6379
      password: ${REDIS_PASSWORD}




