spring:
  application:
    name: catchroom
  datasource:
    url: jdbc-secretsmanager:mysql://catchroomdb.c1aeg6a0abt3.ap-northeast-2.rds.amazonaws.com:3306/catchroomdb
    username: catchroom-secret-manager
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 로컬에서는 해당 부분 level까지는 주석처리 ,배포할때는 풀고 배포
log:
  slack:
    enabled: true
    channel: #error
    web-hook-url: ${{ secrets.SLACK_WEBHOOK_URI}}

  database:
    enabled: true

  level: ERROR
